### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
As promised in my mail, here's the starter package for Fastlane (be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on it). After merging this, I recommend moving the screenshots (currently in `/images`) to `/fastlane/metadata/android/en-US/images/phoneScreenshots/` and update their links in the Readme (as well as wherever else you've linked them), so they become "part of the game" and are updated along whenever needed.

Should you need/want the same starter package for the other project, just let me know :wink:

Oh, and of course feel free to update/adjust to your liking. Some hints on formatting `full_description.txt` can be found [in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane). As you publish to my repo only, you can of course use the full spectrum of Markdown formatting.

### CODE REVIEW

**Comment by frimtec** [comment]
Many thanks for the contribution.

**Comment by IzzySoft** [comment]
Gladly done! I just updated the YAML here to check your Fastlane for each future update. Should you add new "element types" (screenshots, featureGraphic, changelogs) please let me know so I can enable them as well. Btw, if you accept donations, a `.github/FUNDING.yml` is supported by my repo as well :wink:

**Comment by frimtec** [comment]
I added new "element types" screenshots and changelogs. So if you could activate these as well, would be great.

Additionally I also setup the fastlane structure in my other app [PAssist](https://github.com/frimtec/pikett-assist), with the same elements as for S2MSP. So if you could also activate fastlane for PAssist?

Many thanks!

**Comment by IzzySoft** [comment]
> activate these as well, would be great

done (for both).

> fastlane structure in my other app [PAssist](https://github.com/frimtec/pikett-assist)

See my answer per mail. Initial setup done here, short/full desc I'll do once you've fixed the minor issues (else they'll look weird). Just let me know when they're ready. Everything will be pulled then with the next release; if you want it pulled earlier, again let me know and I can trigger that manually.

**Pull request merged**
